[Eth]
NetworkId = 15
SyncMode = "snap"

[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth", "admin", "miner", "presonal"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = "0.0.0.0"
WSPort = 8546
WSModules = ["net", "web3", "eth", "admin", "miner", "presonal"]

[Node.P2P]
NoDiscover = true
