version: '3'
services:
  geth:
    env_file:
      - .env
    build: .
    command:
      --http
      --http.api web3,eth,personal,admin,net,miner
      --http.addr 0.0.0.0
      --http.corsdomain *
      --nodiscover
      --ws
      --ws.api web3,eth,personal,admin,net,miner
      --ws.origins *
      --ws.addr 0.0.0.0
      --allow-insecure-unlock
      --netrestrict=172.16.254.0/24
      --networkid=${NETWORK_ID}
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - geth-data:/root
    container_name: geth
    restart: always
    networks:
      geth-private-net:

networks:
  geth-private-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/24

volumes:
  geth-data:
